services:
  postgres: 
    image: postgres
    container_name: postgres-container  
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER:-postgres} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} 
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
    
    ports: 
    - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

  adminer: 
    image: adminer 
    container_name: adminer-container
    restart: always 
    ports: 
    - 8080:8080 

volumes: 
    postgresql: 